# ML numpy

In [2]:
import numpy as np

In [11]:
a=np.array([8,6,5])
a

array([8, 6, 5])

In [7]:
k=np.array([[3,8,4],[9,3,9],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  9],
       [11, 15, 17],
       [19, 31,  8]])

In [4]:
m=np.array([[[4,4],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]] ])
m

array([[[  4,   4],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [8]:
m.shape

(3, 3, 2)

In [17]:
k[0:5:1,2:] 

array([[ 4],
       [ 9],
       [17],
       [ 8]])

In [15]:
k[0:5:1,2][2]

17

In [15]:
k[2,2]

17

In [16]:
m[1:,1:,:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [14]:
k+5

array([[ 8, 13,  9],
       [14,  8, 14],
       [16, 20, 22],
       [24, 36, 13]])

In [9]:
x=[3,4,5]
x+5

TypeError: can only concatenate list (not "int") to list

In [13]:
a[0]=13
a

array([13,  6,  5])

In [17]:
k=np.array([[3,8,4],[9,3,9],[11,15,17],[19,31,8]])
k

array([[ 3,  8,  4],
       [ 9,  3,  9],
       [11, 15, 17],
       [19, 31,  8]])

In [19]:
k[0:1] =[30,40,50]
k

array([[30, 40, 50],
       [ 9,  3,  9],
       [11, 15, 17],
       [19, 31,  8]])

In [27]:
 k[:,1]=[10,10,10,10]
k

array([[30, 10, 50],
       [ 9, 10,  9],
       [11, 10, 17],
       [19, 10,  8]])

In [28]:
k[:2,1:]=[[101,202],[303,404]]
k

array([[ 30, 101, 202],
       [  9, 303, 404],
       [ 11,  10,  17],
       [ 19,  10,   8]])

In [30]:
np.append(k,[[1,1,1]],axis=0) # 0 to add row wise 

array([[ 30, 101, 202],
       [  9, 303, 404],
       [ 11,  10,  17],
       [ 19,  10,   8],
       [  1,   1,   1]])

In [33]:
np.append(k,[[0],[0],[0],[0]],axis=1)

array([[ 30, 101, 202,   0],
       [  9, 303, 404,   0],
       [ 11,  10,  17,   0],
       [ 19,  10,   8,   0]])

In [34]:
np.delete(k,1,0)

array([[ 30, 101, 202],
       [ 11,  10,  17],
       [ 19,  10,   8]])

In [36]:
np.delete(k,1,1)

array([[ 30, 202],
       [  9, 404],
       [ 11,  17],
       [ 19,   8]])

In [37]:
np.delete(k,3,axis=0)

array([[ 30, 101, 202],
       [  9, 303, 404],
       [ 11,  10,  17]])

In [40]:
k.reshape(6,2)

array([[ 30, 101],
       [202,   9],
       [303, 404],
       [ 11,  10],
       [ 17,  19],
       [ 10,   8]])

In [41]:
a.dtype

dtype('int32')

In [43]:
k1=k.astype('uint16')

In [44]:
k1.dtype

dtype('uint16')

In [45]:
# nutshell
## we create aarays 


In [46]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
np.arange(1,11,1)#will work with float also

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
list(range(1,11,1))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [15]:
np.random.randint(1,6,1)


array([4])

In [16]:
np.random.randint(1,6,[4,3,2])

array([[[2, 5],
        [3, 2],
        [5, 4]],

       [[4, 4],
        [2, 2],
        [4, 1]],

       [[4, 4],
        [2, 3],
        [2, 1]],

       [[3, 4],
        [2, 1],
        [3, 4]]])

In [17]:
np.random.randint(31,6000,[4,3,])

array([[ 862,  106, 5885],
       [5686, 4656, 3444],
       [4786, 5316, 2225],
       [5538, 2580, 2914]])

In [18]:
np.random. seed(10)

In [22]:
np.random. seed(10)
np.random.randint(31,6000,[4,3,])


array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [23]:
np.random.rand(3,4)

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [27]:
a=np.loadtxt('somedata.txt',dtype=str)
a

array(['hi', 'this', 'is', 'pooja'], dtype='<U5')

In [30]:
r=np.loadtxt('moredat.txt')
r

array([[11., 22., 33., 44.],
       [12., 13., 14., 15.]])

In [31]:
p=np.random.rand(3,4)
p

array([[0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715]])

In [32]:
np.savetxt('new.txt',p,delimiter=',')